### ISSUE TITLE
Tarea del módulo 1.1

### ISSUE THREAD

**Issue by rosariom** [SistemasTecTlaxiaco/rosario#1]
¿por qué querrías usar Git en tu salón de clases?
Porque es una herramienta integral y novedosa, para el trabajo colaborativo y el desarrollo de proyectos de ingeniaría de Software
![imagen_2023-06-26_132436470](https://github.com/SistemasTecTlaxiaco/rosario/assets/137822145/67d6eb38-52d9-46f2-a1e5-a13d1e309ef1)

**Comment by josealfredo79** [comment]
Bien echo maestra...excelente
