### ISSUE TITLE
Asignación del modulo 1.2

### ISSUE THREAD

**Issue by rosariom** [SistemasTecTlaxiaco/rosario#2]
Hola

**Comment by rosariom** [comment]
![Captura de pantalla (90)](https://github.com/SistemasTecTlaxiaco/rosario/assets/137822145/5d546f84-827a-4028-9c52-25ea606fe348)
![Captura de pantalla (91)](https://github.com/SistemasTecTlaxiaco/rosario/assets/137822145/6ba57cd4-69e3-4b35-b5eb-7722aead8b07)

**Comment by josealfredo79** [comment]
Bien hecho y revisado maestra....Rosario
