### ISSUE TITLE
Asignación Modulo 2.2.

### ISSUE THREAD

**Issue by rosariom** [SistemasTecTlaxiaco/rosario#6]
![Captura de pantalla (134)](https://github.com/SistemasTecTlaxiaco/rosario/assets/137822145/11aed96c-00c3-41d0-bc64-bbf097d47dfc)
![Uploading Captura de pantalla (132).png…]()
![Captura de pantalla (129)](https://github.com/SistemasTecTlaxiaco/rosario/assets/137822145/3983ee45-df2d-4723-8d71-696155a04202)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
